---
- name: Regular maintenance jobs to be performed on Minecraft Server
  hosts: all
  sudo: yes

  tasks:

  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt: update_cache=yes cache_valid_time=3600

  - name: Update the Minecrat Server - Packages to latest version
    apt: upgrade=dist
    
  - name: Reboot server
    command: /sbin/reboot

  - name: Wait for the server to finish rebooting
    sudo: no
    local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
 
