---
- name: Run the minecraft server with non-root user.
  hosts: all
  sudo: no

  tasks:

  - name: Make minecraft directory
    file: path=~/minecraft state=directory
  
  - name: Get eula.txt set to true
    get_url: url=https://raw.githubusercontent.com/rzfeeser/atpb_minecraft/master/eula.txt dest=~/eula.txt
    
  - name: Download minecraft (1.9.4)
    command: wget -O minecraft_server.jar https://s3.amazonaws.com/Minecraft.Download/versions/1.9.4/minecraft_server.1.9.4.jar chdir=~/minecraft creates=~/minecraft/minecraft_server.jar
    
  - name: Populate launcher
    raw: "ps aux | grep minecraft_server.jar | grep -v grep > launcher.txt"
  
  - name: Set launcher
    stat: path=~/launcher.txt
    register: launcher
  
  - name: Start Minecraft if it is not already up
    command: screen -dmS minecraft java -Xmx1024M -Xms1024M -jar ~/minecraft/minecraft_server.jar nogui
    when: launcher.stat.exists == False
    
  - name: Signal the Minecraft Server is going through a backup in 5 minutes
    command: "screen -S minecraft -X stuff '/say Reticulating splines in 5 minutes.'"
