---
- name: Prepare the Minecraft Server!
  hosts: all
  sudo: yes
  remote_user: minecraft

  tasks:

  - name: Install openjdk-7-jdk
    apt: pkg=openjdk-7-jre state=installed update_cache=true
    
  - name: Install screen
    apt: pkg=screen state=installed update_cache=true
    
  - name: Install git
    apt: name=git state=present

  - name: Download minecraft (1.9.4)
    command: wget -O minecraft_server.jar https://s3.amazonaws.com/Minecraft.Download/versions/1.9.4/minecraft_server.1.9.4.jar chdir=/opt/minecraft creates=/opt/minecraft/minecraft_server.jar
    sudo: no
    
  - name: Run minecraft
    command: screen -S minecraft -d -m java -Xmx512M -Xms512M -jar /opt/minecraft/minecraft_server.jar
    sudo: no
