---
- name: Prepare the Minecraft Server! This should be run as a user without sudo access!
  hosts: all
  sudo: no

  tasks:

  - name: Make minecraft directory
    file: path=~/minecraft state=directory
  
  - name: Get eula.txt set to true
    get_url: url=https://raw.githubusercontent.com/rzfeeser/atpb_minecraft/master/eula.txt dest=~/eula.txt
    
  - name: Download minecraft (1.9.4)
    command: wget -O minecraft_server.jar https://s3.amazonaws.com/Minecraft.Download/versions/1.9.4/minecraft_server.1.9.4.jar chdir=~/minecraft creates=~/minecraft/minecraft_server.jar
    
  - name: Fire and forget minecraft
    command: java -Xmx512M -Xms512M -jar ~/minecraft/minecraft_server.jar nogui
