---
- name: Run the minecraft server with non-root user.
  hosts: all
  sudo: no

  tasks:

  - name: Make minecraft directory
    file: path=~/minecraft state=directory
  
  - name: Get eula.txt set to true
    get_url: url=https://raw.githubusercontent.com/rzfeeser/atpb_minecraft/master/eula.txt dest=~/eula.txt
    
  - name: Download minecraft (1.9.4)
    command: wget -O minecraft_server.jar https://s3.amazonaws.com/Minecraft.Download/versions/1.9.4/minecraft_server.1.9.4.jar chdir=~/minecraft creates=~/minecraft/minecraft_server.jar

  - block:
      - name: pgrep will determine if java (Minecraft Server) is running
        command: pgrep java
    rescue:
      - name: No pgrep!? Start the Minecraft Server!
        command: screen -dmS minecraft java -Xmx1024M -Xms1024M -jar ~/minecraft/minecraft_server.jar nogui

  - name: Make minecraft_backup directory
    file: path=~/minecraft_backup state=directory  

  - name: Signal the Minecraft Sever is going through a save cycle, and perform a live "safe" save.
    command: "screen -S minecraft -X stuff '/say Reticulating splines. \n /save-off \n /save-all \n /save-on \n'"

  ## Build the tar file max once per day & backup to NAS & delete
  - block:
      - name: Tar up the world with the current date
        shell: "tar -cvf ~/minecraft_backup/minecraft_backup$(date +%Y%m%d).tar /home/minecraft/"
    rescue:
      - name: The server needs attention
        debug: msg="Danger! Something regarding the backup of the Minecraft Server has failed!"

  ## You've been saved
  - name: Signal the Minecraft Sever has been backed up
    command: "screen -S minecraft -X stuff '/say Backups have been completed. Entaro Adun.'"
