---
- name: Regular jobs to be performed on Minecraft Server
  hosts: all
  sudo: yes

  tasks:
  
  - name: Signal the Minecraft Server is going down for maintence
  
  - name: Backup the Minecraft Server

  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt: update_cache=yes cache_valid_time=3600

  - name: Update the Minecrat Server - Packages to latest version
    apt: upgrade=dist
