---
- name: Prepare the Minecraft Server!
  hosts: all
  sudo: yes

  tasks:

  - name: Install openjdk-7-jdk
    apt: pkg=openjdk-7-jre state=installed update_cache=true
    
  - name: Install screen
    apt: name=screen state=present
    
  - name: Install git
    apt: name=git state=present
    
  - name: Install fail2ban
    apt: name=fail2ban state=present
    
  - name: Pause
    pause: seconds=2

  - name: Copy fail2ban
    copy: src=/etc/fail2ban/jail.conf dest=/etc/fail2ban/jail.local remote_src=true

  - name: Update fail2ban policy
    lineinfile: dest=/etc/fail2ban/jail.local regexp="^bantime " line="bantime = 7200"
