---
- name: Prepare the Minecraft Server!
  hosts: all
  sudo: yes

  tasks:

  - name: Install openjdk-7-jdk
    apt: pkg=openjdk-7-jre state=installed update_cache=true
    
  - name: Install screen
    apt: pkg=screen state=installed update_cache=true
    
  - name: Install git
    apt: name=git state=present
    
  - name: Install fail2ban
    apt: name=fail2ban
